"use client";
import { Inter } from "next/font/google";
import RootStyleRegistry from "./emotion";
import { SWRConfig } from "swr";
import {  MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en-US">
      <head />
      <body className={inter.className}>
        <RootStyleRegistry>
          <MantineProvider
            theme={{ colorScheme: "dark" }}
            withGlobalStyles
            withNormalizeCSS
          >
            <Notifications />
            <SWRConfig>{children}</SWRConfig>
          </MantineProvider>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
